search_term: open data
search_count: 100
language: en
ignore_spaces: true
save_file: last.tweet
seen_tweets: seen.tweets
max_seen_tweets: 1000
replacements:
  - Open Data: Taylor Swift
  - opendata: TaylorSwift
interval: 60 #seconds
similarity_weighting: 4 # how many words a tweet must overlap already-seen tweets by for us to consider it 'similar'
